language: csharp
solution: PasswordHasher.sln
mono: none
sudo: required
dist: xenial
dotnet: 2.2
script:
    - dotnet restore
    - dotnet build
    - dotnet test TestProject/TestProject.csproj
after_script:
    - dotnet test TestProject/TestProject.csproj
